<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>تحدي الأمن السيبراني — صفحة دخول مخفية</title>
  <style>
    :root{--bg:#071018;--card:#0f1724;--accent:#06b6d4;--ok:#22c55e}
    *{box-sizing:border-box;font-family:Tahoma,Arial,Helvetica,sans-serif}
    body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(180deg,var(--bg),#031022);color:#e6eef8}
    .card{background:rgba(255,255,255,0.02);padding:24px;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,0.6);width:360px;text-align:center}
    h1{margin:0 0 10px;font-size:20px}
    input{width:100%;padding:10px;margin:8px 0;border-radius:8px;border:1px solid rgba(255,255,255,0.04);background:transparent;color:inherit}
    button{width:100%;padding:10px;border-radius:8px;border:none;background:var(--accent);color:#012;cursor:pointer;font-weight:700}
    .hint{margin-top:10px;color:#9ca3af;font-size:13px}
    .flag-box{display:none;margin-top:14px;padding:12px;border-radius:8px;background:linear-gradient(90deg,#052e2e,#064e3b);color:#eafff2}
    .flag-text{font-weight:800;font-size:16px;color:var(--ok)}
    .secret{display:none} /* السلسلة المشفرة مخفية داخل تعليق أدناه */
  </style>
</head>
<body>

<div class="card" id="loginCard">
  <h1>🔒 دخول مشرف (مخفي)</h1>
  <p class="hint">الصفحة جزء من تحدّي — ابحث في شفرة المصدر لتجد السلسلة المشفرة.</p>

  <input id="u" placeholder="اسم المستخدم" autocomplete="off" />
  <input id="p" placeholder="كلمة المرور" type="password" autocomplete="off" />
  <button id="btn">دخول</button>

  <div class="flag-box" id="flagBox">
    <div style="font-size:18px;font-weight:700">🎉 YOU GOT THE FLAG 🎉</div>
    <div class="flag-text" id="flag">FLAG{SECRET_ADMIN_ACCESS}</div>
  </div>

  <p class="hint" id="msg" style="display:none;margin-top:12px;color:#fca5a5"></p>
</div>

<!--
  ! التحدّي:
  ! هذه السلسلة هي نتيجة XOR مع مفتاح ثلاثي الأحرف ثم تشفير Base64.
  ! السلسلة المشفّرة (ضعها هنا لكي يراها الطلاب عند فتح Page Source):
  encoded_payload = ClcUAl1DCEobDkFIWQA=
  ! تلميح: فكّ Base64 ثم جرّب تطبيق XOR على البايتات للحصول على نص مثل "username:password"
-->

<script>
/*
  الشيفرة تتحقق من صحة بيانات المستخدم بعد فكّها داخلياً.
  الهدف: الطالب يجد السلسلة المشفّرة أعلاه في مصدر الصفحة، يفك Base64،
  ثم يطبق XOR بنفس المفتاح ليحصل على النص الحقيقي على الشكل: "admin:cyber123"
  عند إدخالهما يظهر العلم.
*/

/* ********* الدالة المساعدة لتحويل سلسلة Base64 إلى مصفوفة بايت ********* */
function base64ToBytes(b64) {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

/* ********* XOR بايت-بايت ********* */
function xorBytes(bytes, keyBytes) {
  const out = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) {
    out[i] = bytes[i] ^ keyBytes[i % keyBytes.length];
  }
  return out;
}

/* ********* تحويل بايتس إلى نص UTF-8 ********* */
function bytesToString(bytes) {
  // بسيطة: نفترض محارف ascii/utf-8 بسيطة
  return String.fromCharCode.apply(null, bytes);
}

/* ********* هنا السلسلة المشفّرة — نفس السلسلة المذكورة في التعليق أعلاه ********* */
const encoded_payload = "ClcUAl1DCEobDkFIWQA=";

/* ********* المفتاح مخزّن هنا لكن بصيغة أرقام حتى لا يظهر كنص واضح فوراً *********
   هذا إخفاء بسيط: المفتاح هو الأحرف ذات كودات 107, 51, 121  => 'k','3','y'
   (المعلم بإمكانه تغيير هذه الأرقام لجعل المفتاح مختلفاً) */
const keyCharCodes = [107, 51, 121]; // 'k','3','y'

// نبني مصفوفة بايت للمفتاح
const keyBytes = new Uint8Array(keyCharCodes);

/* نفك السلسلة الآن (سيتم استخدامها لمطابقة الإدخال) */
const encBytes = base64ToBytes(encoded_payload);
const plainBytes = xorBytes(encBytes, keyBytes);
const plainText = bytesToString(plainBytes); // متوقع شكل "username:password"

// نفصل إلى اسم مستخدم وكلمة مرور حقيقية
let realUser = "";
let realPass = "";
if (plainText.includes(":")) {
  const parts = plainText.split(":");
  realUser = parts[0];
  realPass = parts.slice(1).join(":");
} else {
  // في حال لم يتحول النص كما هو متوقع — لا شيء
  realUser = "";
  realPass = "";
}

/* ***** عملية التحقق عند الضغط على زر الدخول ***** */
document.getElementById("btn").addEventListener("click", function(){
  const u = document.getElementById("u").value.trim();
  const p = document.getElementById("p").value.trim();
  const msg = document.getElementById("msg");
  if (!realUser) {
    msg.style.display = "block";
    msg.textContent = "خطأ في التهيئة — اجعل المعلم يتحقق من السلسلة المشفّرة.";
    return;
  }
  if (u === realUser && p === realPass) {
    document.getElementById("flagBox").style.display = "block";
    msg.style.display = "none";
  } else {
    msg.style.display = "block";
    msg.textContent = "اسم المستخدم أو كلمة المرور خاطئ. جرّب فكّ السلسلة في مصدر الصفحة.";
  }
});

/* ملاحظة للمدرّس: لتغيير الاعتماديات ببساطة:
   1) عدّل النص المرغوب 'username:password'
   2) طبّق XOR بالمفتاح (نفس طول المفتاح) ثم حول النتيجة إلى Base64
   3) استبدل قيمة encoded_payload بالقيمة الناتجة
   4) إن أردت تغيير المفتاح غيّر keyCharCodes إلى أرقام أخرى
*/
</script>

</body>
</html>
